title: Pentest Günlüğüm
description: "Blog about cyber security stuff"
author:
  name: "Funda EREN"
  email: "pentestgunlugum@gmail.com"
  url: "https://github.com/fundaeren/fun"

baseurl: /

google_analytics: UA-155400528-1
source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

owner : "ls4cfk"
year : "2020"
